### ISSUE TITLE
Unable to download - 404 Not Found error (and fix)

### ISSUE THREAD

**Issue by WmBA** [qcri-social/AIDR#32]
I am unable access the download file that is generated.  Hyperlink generates this error ...

The requested URL /AIDRPersister/data/persister/150615114921_test_-_flood_detection/150615114921_test_-_flood_detection_tweetIds_filtered-51af4fe543ce9441966cc54e2c3c68aa.csv.zip was not found on this server.

Supplying the root domain instead of the AIDRPersister (which I assume is a proxy) for the URL fixes the issue.

aidr-prod.qcri.org/data/persister/150615114921_test_-_flood_detection/150615114921_test_-_flood_detection_tweetIds_filtered-51af4fe543ce9441966cc54e2c3c68aa.csv.zip

Although the file contents for this id only file is a bit puzzling (I'll play with that issue some more) this at least gets the file down,

**Comment by koushiksinha** [comment]
Thanks for reporting this bug. We will fix the issue asap.

Regards,
AIDR Team

-----Original Message-----

**Comment by meghnas** [comment]
This issue has been resolved
