### ISSUE TITLE
Issues with Sign-in and missing DB table

### ISSUE THREAD

**Issue by akhtet** [qcri-social/AIDR#54]
Hi AIDR Team,

I have been trying to run AIDR on my own server but having some technical issues. Basically, I've got NullPointerExceptions / Internal Server Error while opening the AIDR Fetch Manager URL. Glassfish server logs contain the same exception trail as this one - https://java.net/jira/browse/GLASSFISH-21522. Please let me know if you encountered this in aidr-prod and have resolved it somehow.

It also appears that there have been no updates to the source code for a while. Are there any plans to do updates in the near future?

**Comment by jikimlucas** [comment]
Hello Akhet!
We have been working on major changes on our system. So, we didn't push any change yet due to stability. once we complete the upgrade, we will merge the code.

Re your issue. could you post log info and details so that one of our team can assist you.

Thank you,

**Comment by akhtet** [comment]
Thank you @jikimlucas / Team.

I have two issues with my own deployment of AIDR. Please let me know if you have any suggestions how to solve this.

**(1) AIDR_COLLECTION table does not exist.**
While running deploy.sh deploy deploy_db, I get the following error message at the end.
`ERROR 1146 (42S02) at line 154: Table 'aidr_fetch_manager.AIDR_COLLECTION' doesn't exist`

Java exceptions also exist in the aidr-manager.log saying this table does not exist.
`ERROR [scheduler-1][qa.qcri.aidr.manager.util.ScheduledTask][scheduledTaskUpdateCollections] - Error while executing update collections scheduled task
org.hibernate.exception.SQLGrammarException: could not execute query
        at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:92)`

`Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'aidr_fetch_manager.AIDR_COLLECTION' doesn't exist
        at sun.reflect.GeneratedConstructorAccessor589.newInstance(Unknown Source)
`



**(2) Cannot login to AIDR Fetch Manager.**
I visited `AIDRFetchManager/index.jsp` and clicked Sign-in with Twitter. But then I got redirected immediately to `AIDRFetchManager/signin?error=provider`

In the aidr-manager.log, the following message is repeated.
`WARN  [http-listener-1(3)][org.springframework.web.client.RestTemplate][handleResponseError] - POST request for "https://api.twitter.com/oauth/request_token" resulted in 401 (Authorization Required); invoking error handler`

Prior to this, I have already added Twitter consumer key and secret, and rebuilt the app before deploying.

**Comment by kushalkantgoyal** [comment]
Hi Aung,
Please find the attached db_scripts.

First execute the aidr_dump.sql and then aidr_seed_data.sql.

This may resolve your issues.

**Comment by akhtet** [comment]
Hi @kushalkantgoyal 

Would you be able to attach these sql scripts in this thread? I believe they have not been attached in your post. Thank you!

**Comment by kushalkantgoyal** [comment]
Can you please provide your email-id since github is not allowing sql files in attachment.

**Comment by akhtet** [comment]
Hi @kushalkantgoyal . Thanks a lot. This solved the first issue .i.e AIDR_COLLECTION table does not exist.

Still having the other issue. i.e. unable to sign-in with twitter.
`
2016-04-05 12:56:53 WARN  [http-listener-1(2)][org.springframework.web.client.RestTemplate][handleResponseError] - POST request for "https://api.twitter.com/oauth/request_token" resulted in 401 (Authorization Required); invoking error handler
`
Any suggestions would be appreciated.

**Comment by akhtet** [comment]
Hi @kushalkantgoyal I followed your suggestion to refresh the twitter keys. After creating a new twitter app (including new consumer keys,) the OAuth seems to work now. We can now log-on to our own AIDR instance and test run some collections from Twitter. We'll keep you posted if we find anything new. Thanks again for your help.
